version: '3'

services:
  fastapi:
    build: ./fastapi
    container_name: medical-fast
    ports:
      - "8000:8000"
    networks:
      - medical-network

  nextjs:
    build: ./med_diagnosis
    container_name: medical-next
    ports:
      - "3000:3000"
    networks:
      - medical-network

networks:
  medical-network:
